### ISSUE TITLE
Jest with "node" testEnvironment

### ISSUE THREAD

**Issue by zertosh** [facebooknuclide/nuclide-format-js#2]
No idea why it doesn't work.

**Comment by zertosh** [comment]
When I set `"testEnvironment": "node"`, I get this error:

```
$ node_modules/.bin/jest
 PASS  __tests__/updateCursor-test.js
 FAIL  __tests__/requiresTransform-spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at runInContext (node_modules/lodash/index.js:718:27)
      at Object.<anonymous> (node_modules/lodash/index.js:12320:11)
      at Object.<anonymous> (node_modules/lodash/index.js:12351:3)
      at Object.<anonymous> (node_modules/jscodeshift/dist/Collection.js:21:9)

 PASS  __tests__/reprint-spec.js
 FAIL  __tests__/options-spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      at runInContext (node_modules/lodash/index.js:718:27)
      at Object.<anonymous> (node_modules/lodash/index.js:12320:11)
      at Object.<anonymous> (node_modules/lodash/index.js:12351:3)
      at Object.<anonymous> (node_modules/jscodeshift/dist/Collection.js:21:9)

Test Summary
 › Ran all tests.
 › 2 test suites failed, 58 tests passed (58 total in 4 test suites, run time 3.985s)
```

@cpojer this is https://github.com/facebook/jest/issues/1597, right?

**Comment by cpojer** [comment]
Yeah that is the same issue.

**Comment by cpojer** [comment]
See https://github.com/facebook/jest/pull/2021

**Comment by cpojer** [comment]
fyi this was fixed!
